name: Deployment for ContainerApp

# When this action will be executed
on:
  workflow_run:
    workflows: [Docker Image CI]
    types:
      - completed

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:

  deploy:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FILESERVERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n asecondtry -g file-upload-app --server fileuploadapp.azurecr.io --username  ${{ secrets.FILESERVERAPP_REGISTRY_USERNAME }} --password ${{ secrets.FILESERVERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n asecondtry -g file-upload-app --image fileuploadapp.azurecr.io/fileserver:${{ github.sha }}
