name: Trigger auto deployment for fileserver-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fileserver-app-AutoDeployTrigger-26e8bc69-7524-4957-b8fa-becf9a6fceba.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: fileuploadapp.azurecr.io
          username: ${{ secrets.FILESERVERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.FILESERVERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fileuploadapp.azurecr.io/fileserver:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FILESERVERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n fileserver-app -g file-upload-app --server fileuploadapp.azurecr.io --username  ${{ secrets.FILESERVERAPP_REGISTRY_USERNAME }} --password ${{ secrets.FILESERVERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n fileserver-app -g file-upload-app --image fileuploadapp.azurecr.io/fileserver:${{ github.sha }}
